### ISSUE TITLE
Fix unity install

### ISSUE THREAD

**Issue by lfriesecke** [konradgithuup/Penguin-Madness-Bezier-Orbital-King#1]

**Comment by konradgithuup** [comment]
>No description provided
🐳💨

**Comment by konradgithuup** [comment]
worksforme
![timurjam](https://media.discordapp.net/attachments/345642521579225089/906716489736945734/timurjam.gif?ex=65da9789&is=65c82289&hm=b5704e737e9992bbbbea33127a106778b057f6a97cf200586a4f2e8caa4c9845&)
